name="Custom Start Page Tools"
author="MrJeranimo"
version="0.1.1"
description="A mod that replaces the default start page with a custom page to expand start page functionality."

[StarMap]
EntryAssembly="Custom Start Page Tools"